#!/bin/bash

which vim || echo "err: vim не найден" & exit 1
which go || echo "err: Сборка не возможна, go не установлен" & ext 1
which cat || echo "err: cat не установлен" & exit 1
which openrc || echo "Скрипт пока только под openrc" & exit 1

go build system/openrc/systemctl
sudo cp system/openrc/systemctl /usr/local/bin/

