#!/bin/bash
# /usr/local/bin/journalctl

while [ $# -gt 0 ]; do
    case $1 in
        -f|--follow)
            tail -f /var/log/messages
            exit 0
            ;;
        -u|--unit)
            shift
            grep "$1" /var/log/messages | tail -50
            exit 0
            ;;
        --since)
            shift
            if [ "$1" = "today" ]; then
                grep "$(date '+%b %d')" /var/log/messages
            elif [ "$1" = "yesterday" ]; then
                grep "$(date -d 'yesterday' '+%b %d')" /var/log/messages
            else
                echo "Поддерживается только --since today|yesterday"
                exit 1
            fi
            exit 0
            ;;
        -n|--lines)
            shift
            tail -n "$1" /var/log/messages
            exit 0
            ;;
        -p|--priority)
            shift
            grep -i "$1" /var/log/messages
            exit 0
            ;;
        *)
            grep "$1" /var/log/messages
            exit 0
            ;;
    esac
    shift
done

tail -n 50 /var/log/messages
