#!/bin/bash

#systemctl enable
enable_service() {
    local service_name="$1"
    rc-update add "$service_name" default
}

#systemctl disable
disable_service() {
    local service_name="$1"
    rc-update del "$service_name" default
}

#systemctl start
start_service() {
    local service_name="$1"
    rc-service "$service_name" start
}

#systemctl stop
stop_service() {
    local service_name="$1"
    rc-service "$service_name" stop
}

#systemctl restart
restart_service() {
    local service_namecp INST.sh /root="$1"
    rc-service "$service_name" restart
}

#systemctl status
status_service() {
    local service_name="$1"
    rc-service "$service_name" status
}

case "$1" in
    enable)
        shift
        enable_service "$1"
        ;;
    disable)
        shift
        disable_service "$1"
        ;;
    start)
        shift
        start_service "$1"
        ;;
    stop)
        shift
        stop_service "$1"
        ;;
    restart)
        shift
        restart_service "$1"
        ;;
    status)
        shift
        status_service "$1"
        ;;
    *)
        echo "Usage: systemctl {enable|disable|start|stop|restart|status} <service_name>"
        exit 1
        ;;
esac
